Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace Library_Management_System_MVC.Models
{
    public class Book
    {
        //Yayınlanma tarihi Constructer ile 
        public Book() 
        {
            PublishDate = DateTime.Now;
        }


        public int Id { get; set; }
        public string Title { get; set; }
        public int AuthorId { get; set; }
        public string Genre { get; set; }
        public DateTime PublishDate { get; set; }
        public string ISBN { get; set; }
        public int CopiesAvailable { get; set; }


    }
}

Controllers/AuthorController.cs
using Library_Management_System_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library_Management_System_MVC.Controllers
{
    public class AuthorController : Controller
    {
        public static List<Author> authors = new List<Author>
        {
            new Author { Id = 1, FirstName = "George", LastName = "Orwell", DateOfBirth = new DateTime(1903, 6, 25) },
            new Author { Id = 2, FirstName = "J.K.", LastName = "Rowling", DateOfBirth = new DateTime(1965, 7, 31) },
            new Author { Id = 3, FirstName = "Agatha", LastName = "Christie", DateOfBirth = new DateTime(1890, 9, 15) },
            new Author { Id = 4, FirstName = "Stephen", LastName = "King", DateOfBirth = new DateTime(1947, 9, 21) },
            new Author { Id = 5, FirstName = "George", LastName = "Orwell", DateOfBirth = new DateTime(1903, 6, 25) },
            new Author { Id = 6, FirstName = "J.K.", LastName = "Rowling", DateOfBirth = new DateTime(1965, 7, 31) },
            new Author { Id = 7, FirstName = "Agatha", LastName = "Christie", DateOfBirth = new DateTime(1890, 9, 15) },
            new Author { Id = 8, FirstName = "Stephen", LastName = "King", DateOfBirth = new DateTime(1947, 9, 21) },
            new Author { Id = 9, FirstName = "J.R.R.", LastName = "Tolkien", DateOfBirth = new DateTime(1892, 1, 3) },
            new Author { Id = 10, FirstName = "Isaac", LastName = "Asimov", DateOfBirth = new DateTime(1920, 1, 2) },
            new Author { Id = 11, FirstName = "Ray", LastName = "Bradbury", DateOfBirth = new DateTime(1920, 8, 22) },
            new Author { Id = 12, FirstName = "Harper", LastName = "Lee", DateOfBirth = new DateTime(1926, 4, 28) }


        };
        public IActionResult List()
        {
            var viewModel =authors.Select(x=> new AuthorViewModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                DateOfBirth =  x.DateOfBirth
            } ).ToList();
            return View(viewModel);
        }
        
        public IActionResult Details(int id)
        {
            var author = authors.FirstOrDefault(a => a.Id == id);
            if (author == null) return NotFound();

            var books = BookController.books.Where(b => b.AuthorId == author.Id).ToList();
            //Yazarın kitaplarını gösteren bir viewmodel oluşturuldu.
            var viewModel = new AuthorDetailsViewModel
            {
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                DateOfBirth = author.DateOfBirth,
                Books = books
            };

            return View(viewModel);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AuthorCreateViewModel model)
        {


            if (ModelState.IsValid)
            {
                // Yeni bir yazar nesnesi oluşturuyoruz.
                var newAuthor = new Author
                {
                    Id = authors.Count + 1,  // ID, mevcut yazar sayısına göre belirleniyor
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    DateOfBirth = model.DateOfBirth
                };

                // Yazar listesine ekliyoruz.
                authors.Add(newAuthor);

                // Yazarlar listesini gösteren sayfaya yönlendiriyoruz.
                return RedirectToAction("List");
            }

            // Model geçerli değilse, kullanıcıya aynı formu tekrar gösteriyoruz.
            return View(model);
        }


        //Update işlemi için
        public IActionResult Update(int id)
        {// Güncellenecek yazarı buluyoruz.
            var author = authors.FirstOrDefault(a => a.Id == id);
            if (author == null) return NotFound();
            
            var viewAuthorUpdateViewModel = new AuthorUpdateViewModel
            {
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                DateOfBirth = author.DateOfBirth
            };

            return View(viewAuthorUpdateViewModel);
        }
        //Update işlemi için
        [HttpPost]
        public IActionResult Update(AuthorUpdateViewModel formData) 
        {
            // Güncellenecek yazarı buluyoruz.
            var author = authors.FirstOrDefault(a => a.Id == formData.Id);
            if (author == null) return NotFound();
            // Yazarın bilgilerini güncelliyoruz.
            author.FirstName = formData.FirstName;
            author.LastName = formData.LastName;
            author.DateOfBirth = formData.DateOfBirth;
            // Yazarlar listesini gösteren sayfaya yönlendiriyoruz.
            return RedirectToAction("List");
        }
        //Delete işlemi için
        public IActionResult Delete(int id) 
        {
            // Silinecek yazarı buluyoruz.
            var author = authors.FirstOrDefault(a => a.Id == id);
            // Eğer yazar bulunamazsa NotFound döndürüyoruz.
            if (author == null) return NotFound();
            // Yazarı gösteren sayfayı gösteriyoruz.
            return View(author);
        }

     
        [HttpPost]
        public IActionResult Delete(Author author)
        {
            // Silinecek yazarı buluyoruz.
            var authorToDelete = authors.FirstOrDefault(a => a.Id == author.Id);
            // Eğer yazar bulunamazsa NotFound döndürüyoruz.
            if (authorToDelete == null) return NotFound();
            // Yazarı listeden siliyoruz.
            authors.Remove(authorToDelete);
            // Yazarlar listesini gösteren sayfaya yönlendiriyoruz.
            return RedirectToAction("List");
        }

    }

}

Controllers/BookController.cs
using Library_Management_System_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library_Management_System_MVC.Controllers
{

    public class BookController : Controller
    {
        //Geçici olarak kitapları burada tutuyoruz.
        public static List<Book> books = new List<Book>
        {
        new Book{ Id = 1, Title = "1984", AuthorId = 1, Genre = "Dystopian", ISBN = "1234567890", CopiesAvailable = 5 },

        new Book{ Id = 2, Title = "Animal Farm", AuthorId = 1, Genre = "Political Satire", ISBN = "0987654321", CopiesAvailable = 3 },

        new Book{ Id = 3, Title = "Harry Potter and the Philosopher's Stone", AuthorId = 2, Genre = "Fantasy",  ISBN = "1357924680", CopiesAvailable = 7 },

        new Book{ Id = 4, Title = "Harry Potter and the Chamber of Secrets", AuthorId = 2, Genre = "Fantasy", ISBN = "2468135790", CopiesAvailable = 4 },

        new Book { Id = 5, Title = "1984", AuthorId = 1, Genre = "Dystopian", ISBN = "1234567890", CopiesAvailable = 5 },

        new Book { Id = 6, Title = "Harry Potter and the Philosopher's Stone", AuthorId = 2, Genre = "Fantasy", ISBN = "9876543210", CopiesAvailable = 3 },

        new Book { Id = 7, Title = "Murder on the Orient Express", AuthorId = 3, Genre = "Mystery", ISBN = "2468135791", CopiesAvailable = 4 },

        new Book { Id = 8, Title = "The Shining", AuthorId = 4, Genre = "Horror", ISBN = "1122334455", CopiesAvailable = 6 },

        new Book { Id = 9, Title = "Animal Farm", AuthorId = 1, Genre = "Political Satire", ISBN = "3344556677", CopiesAvailable = 7 },

        new Book { Id = 10, Title = "Fantastic Beasts and Where to Find Them", AuthorId = 2, Genre = "Fantasy",  ISBN = "5566778899", CopiesAvailable = 3 },

        new Book { Id = 11, Title = "The Murder of Roger Ackroyd", AuthorId = 3, Genre = "Mystery", ISBN = "9988776655", CopiesAvailable = 4 },

        new Book { Id = 12, Title = "It", AuthorId = 4, Genre = "Horror", ISBN = "2233445566", CopiesAvailable = 5 }








        };


        public IActionResult List()
        {
            
            //Select kullanarak her bir kitap için yeni bir booklistviewmodel olustur.
            var viewModel = books.Select(x => new BookListViewModel
            {
                Id = x.Id,
                Title = x.Title,
                 
                Author = AuthorController.authors.FirstOrDefault(y => y.Id == x.AuthorId),
                Genre = x.Genre,
                PublishDate = x.PublishDate,
                ISBN = x.ISBN,
                CopiesAvailable = x.CopiesAvailable

            }).ToList();

            return View(viewModel);

        }
        
        public IActionResult Details(int id)
        {
            //eşleşen ıd bulucak bulamazsa null dönecek. FirstOrDefault
            var book = books.FirstOrDefault(x => x.Id == id);
            if (book == null) return NotFound();

            var viewModel = new BookDetailsViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Author = AuthorController.authors.FirstOrDefault(y => y.Id == book.AuthorId),
                Genre = book.Genre,
                PublishDate = book.PublishDate,
                ISBN = book.ISBN,
                CopiesAvailable = book.CopiesAvailable
            };

            return View(viewModel);

        }
        //HttpGet isteği ile kitap eklemek için formu göterdik
        public IActionResult Create()
        {
            var viewModel = new BookCreateViewModel
            {
                Authors = AuthorController.authors.Select(x => new AuthorViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    LastName = x.LastName

                }).ToList()
            };

            return View(viewModel);
        }

        //Formdan gelen buton bu Action'ı tetikleyecek [HttpPost]
        [HttpPost]
        public IActionResult Create(BookCreateViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                formData.Authors = AuthorController.authors.Select(x => new AuthorViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    LastName = x.LastName

                }).ToList();

                return View(formData);
            }

            
            
            

            var newBook = new Book
            {
                //Id var ise en büyük id'ye 1 ekle yok ise id "1" olsun. 
                Id = books.Any() ? books.Max(b => b.Id) + 1 : 1,
                Title = formData.Title,
                AuthorId = formData.AuthorId,
                Genre = formData.Genre,
                ISBN = formData.ISBN,
                CopiesAvailable = formData.CopiesAvailable
            };

            books.Add(newBook);//listeye eklendi 
            return RedirectToAction("List");//yönlendirme yapıldı.
        }



        //Güncelleme işlemi için id ye ihtiyacımız var.
        public IActionResult Update(int id)
        {
            //eşleşen id bulucak bulamazsa null dönecek. FirstOrDefault
            var bookUpdate = books.FirstOrDefault(x => x.Id == id);
            //bulamazsa hata dönecek
            if (bookUpdate == null) return NotFound();
            //Güncelleme işlemi için viewmodel oluşturuldu.
            var varBookUpadateViewModel = new BookUpdateViewModel
            {
                
                Id = bookUpdate.Id,
                Title = bookUpdate.Title,
                AuthorId = bookUpdate.AuthorId,
                Genre = bookUpdate.Genre,
                CopiesAvailable = bookUpdate.CopiesAvailable,
                 Authors = AuthorController.authors.Select(x => new AuthorViewModel
                 {
                     Id = x.Id,
                     FirstName = x.FirstName,
                     LastName = x.LastName

                 }).ToList()
            };
            //Güncelleme işlemi için view gönderildi.
            return View(varBookUpadateViewModel);
        }
        //Güncelllemede açılır listede yazarlar gelmiyor.//Düzeltildi
        [HttpPost]
        public IActionResult Update(BookUpdateViewModel formData)
        {
            var bookUpdate = books.FirstOrDefault(x => x.Id == formData.Id);
            if (bookUpdate == null) return NotFound();//bulamazsa hata dönecek

            bookUpdate.Title = formData.Title;
            bookUpdate.AuthorId = formData.AuthorId;
            bookUpdate.Genre = formData.Genre;
            bookUpdate.CopiesAvailable = formData.CopiesAvailable;

            return RedirectToAction("List");
        }



        //Silme işlemi için id ihticımız var.
        
        public IActionResult Delete(int id)
        {
            var bookDelete = books.FirstOrDefault(x => x.Id == id);//eşleşen id bulunuyor.
            if (bookDelete == null) return NotFound();//bulamazsa hata dönecek

            return View(bookDelete);
        }
        
        [HttpPost]
        public IActionResult Delete(Book book)
        {
            var bookDelete = books.FirstOrDefault(x => x.Id == book.Id);
            if (bookDelete != null)
            {
                books.Remove(bookDelete);
            }

            return RedirectToAction("List");
        }
        
    }
}

Views/Book/Create.cshtml
@model BookCreateViewModel




@*method=post ile veriyi taşıma yöntemimizi post seçtik.*@
<form method="post" asp-controller="Book" asp-action="Create">
    @*Tüm hataları üste sırala dedik summary ile*@
    <div asp-validation-summary="All" class="text-danger">

    </div>

    <div class="form-group">
        <label for="Title">Kitap Adı</label>
        @*BookCreateViewModel deki Title'a  eşledik*@
        <input asp-for="Title" class="form-control"  />
        <span asp-validation-for="Title" class="text-danger" ></span>
        @*Title'a ait hata mesajını göstermek için span kullandık.Böylelikle hem üste hatalar sıralandı hemde altlarında*@
    </div>

    <div class="form-group">
        <label for="AuthorId">Yazar</label>
        <select asp-for="AuthorId" class="form-control" asp-items="@(new SelectList(Model.Authors, "Id", "FullName"))" >
            <option value="">Seçiniz...</option>
        </select>
    </div>

    <div class="form-group">
        <label for="Genre">Tür</label>
        <input asp-for="Genre" class="form-control"  />
        <span asp-validation-for="Genre" class="text-danger"   ></span>
    </div>

    <div class="form-group">
        <label for="ISBN">ISBN</label>
        <input asp-for="ISBN" class="form-control" />
        <span asp-validation-for="ISBN" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="CopiesAvailable">Kopya Sayısı</label>
        <input asp-for="CopiesAvailable" class="form-control"  />
        <span asp-validation-for="CopiesAvailable" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-warning mt-4 fw-bold float-end">Kitap Ekle</button>
</form>

Views/Book/Delete.cshtml
@model Book


<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header bg-danger text-white">
            <h3><i class="bi bi-exclamation-triangle-fill"></i> Kitap Sil</h3>
        </div>
        <div class="card-body">
            <p class="fs-5"> "<strong>@Model.Title</strong>" kitabını silmek istediğinize emin misiniz?</p>

            <form asp-action="Delete" method="post">
                <input type="hidden" asp-for="Id" />

                
                <div class="mb-3">
                    <label class="form-label">Başlık</label>
                    <input asp-for="Title" class="form-control" disabled /> @*disabled yapıldı.input alanı sadece görüntülenebilir*@
                </div>

                

                <div class="mb-3">
                    <label class="form-label">Tür</label>
                    <input asp-for="Genre" class="form-control" disabled />
                </div>

                
                <div class="mb-3">
                    <label class="form-label">ISBN</label>
                    <input asp-for="ISBN" class="form-control" disabled />
                </div>

              
                <div class="mb-3">
                    <label class="form-label">Mevcut Kopya</label>
                    <input asp-for="CopiesAvailable" class="form-control" disabled />
                </div>

                
                <div class="d-flex justify-content-center gap-3">
                    <button type="submit" class="btn btn-danger">
                        <i class="bi bi-trash"></i> Sil
                    </button>
                    <a asp-controller="Book" asp-action="List" class="btn btn-dark">
                        <i class="bi bi-arrow-left"></i> İptal
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Book/Details.cshtml
@model BookDetailsViewModel

<div class="container mt-5">
    <div class="card shadow-lg">
       
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">@Model.Title</h4>
        </div>
        <div class="card-body">
            <p><strong>Yazar:</strong> @Model.AuthorName</p>
            <p><strong>Tür:</strong> @Model.Genre</p>
            <p><strong>Yayın Tarihi:</strong> @Model.PublishDate.ToShortDateString()</p>
            <p><strong>ISBN:</strong> @Model.ISBN</p>
            <p><strong>Mevcut Kopya:</strong> @Model.CopiesAvailable</p>
        </div>
        <div class="card-footer text-end">
        
  
            <a asp-controller="Book" asp-action="Update" asp-route-id="@Model.Id" class="btn btn-warning">
                <i class="bi bi-pencil-square"></i> Güncelle
            </a>
          
            <a asp-controller="Book" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger" onclick="return confirm('Bu kitabı silmek istediğinizden emin misiniz?');">
                <i class="bi bi-trash"></i> Sil
            </a>
        </div>
    </div>
</div>

Views/Book/List.cshtml
@model List<BookListViewModel>

    <partial name ="_BannerPartial" />
<div class="text-center mt-4">
    <a class="btn btn-danger" asp-controller="Book" asp-action="Create">Kitap Ekle</a>
    <a class="btn btn-secondary" asp-controller="Author" asp-action="Create">Yazar Ekle</a>
</div>

<div class="container mt-4">
    <h4 class="mb-4 text-danger">Kitap Listesi</h4>

    <table class="table table-striped table-hover shadow-sm">
        <thead class="bg-danger text-white">
            <tr>
                <th class="text-danger">Başlık</th>
                <th class="text-danger">Yazar</th>
                <th class="text-danger">Tür</th>
                <th class="text-danger">Yayın Tarihi</th>
                <th class="text-danger">ISBN</th>
                <th class="text-danger">Kopya Sayısı</th>
                <th class="text-danger text-center">İşlemler</th>
            </tr>
        </thead>
        <tbody class="bg-light">
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.AuthorName</td>
                    <td>@book.Genre</td>
                    <td>@book.PublishDate.ToShortDateString()</td>
                    <td>@book.ISBN</td>
                    <td>@book.CopiesAvailable</td>
                    <td class="text-center">
                        <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id"  class="btn btn-info btn-sm">
                            <i class="bi bi-eye"></i> Detaylar
                        </a>
                        <a asp-controller="Book" asp-action="Update" asp-route-id="@book.Id" class="btn btn-warning btn-sm">
                            <i class="bi bi-pencil"></i> Güncelle
                        </a>
                        <a asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-danger btn-sm" onclick="return confirm('Bu kitabı silmek istediğinizden emin misiniz?');">
                            <i class="bi bi-trash"></i> Sil
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Book/Update.cshtml
@model BookUpdateViewModel

<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header bg-warning text-dark">
            <h4 class="mb-0">Kitap Güncelle</h4>
        </div>
        <div class="card-body bg-light">
            <form method="post">
                @*Güncellemede Id dönüyor bu yüzden hidden ile gizlendi.*@
                <input type="hidden" asp-for="Id" />

                <div class="mb-3">
                    <label class="form-label text-warning">Başlık</label>
                    <input type="text" class="form-control border-secondary" asp-for="Title"  />
                </div>

                <div class="form-group">
                    <label for="AuthorId">Yazar</label>
                    @*1. Listem 2.Gömek istediğim veri 3.görmek istediğim asp-item SelectList newlendi constructor*@
                    <select asp-for="AuthorId" class="form-control" asp-items="@(new SelectList(Model.Authors, "Id", "FullName"))" >
                        <option value="">Seçiniz...</option>
                    </select>
                </div>

                <div class="mb-3">
                    <label class="form-label text-warning">Tür</label>
                    <input type="text" class="form-control border-secondary" asp-for="Genre" />
                </div>

                <div class="mb-3">
                    <label class="form-label text-warning">Mevcut Kopya Sayısı</label>
                    <input type="number" class="form-control border-secondary" asp-for="CopiesAvailable" min="0"  />
                </div>

                <div class="text-end">
                    <a asp-controller="Book" asp-action="List" class="btn btn-secondary">
                        <i class="bi bi-arrow-left"></i> Geri
                    </a>
                    <button type="submit" class="btn btn-warning">
                        <i class="bi bi-check-circle"></i> Kaydet
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>